import './globals.css'
import type { Metadata } from 'next'
import { Inter } from 'next/font/google'
import { AccountContextProvider } from './context/account.context'

const inter = Inter({ subsets: ['latin'] })

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
}

export default function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
  return (
    <html suppressHydrationWarning={true} lang="en">
      <body suppressHydrationWarning={true} className={inter.className}>
        <AccountContextProvider>
          {children}
        </AccountContextProvider>
      </body>
    </html>
  )
}
